/**
 *
 * @type {{MISSING_TOKEN: string, INVALID_TOKEN_SCHEMA: string, INVALID_TOKEN: string, TOKEN_BLACKLISTED: string, UNKNOWN_ERROR: string}}
 */
module.exports = {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    MISSING_TOKEN: 'MISSING_TOKEN',
    INVALID_TOKEN_SCHEMA: 'INVALID_TOKEN_SCHEMA',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_BLACKLISTED: 'TOKEN_BLACKLISTED',
};